site:
  title: NBNL Modellen â€” Dataproducten
  url: https://modellen.netbeheernederland.nl/dataproducten
content:
  sources:
    - url: .
      start_paths: [src/root_component/_]
asciidoc:
  attributes:
    page-pagination: ''
    experimental: ''
    kroki-fetch-diagram: true
    kroki-default-format: svg@
    kroki-server-url: http://fruit.ritger.nl:9000
  extensions:
    - asciidoctor-kroki
    - '@djencks/asciidoctor-mathjax'
output:
  clean: true
  dir: output/docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: supplemental-ui
